networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
          gateway: 172.50.0.1

volumes:
  localstack:
    driver: local

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:3.0.2
    networks:
      default:
        ipv4_address: 172.50.0.2
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      # - "127.0.0.1:4566:4566"            # LocalStack Gateway
      # - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - ACTIVATE_PRO=0
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
